const BITS_PER_BYTE = 8;
const AES_KW_INTEGRITY_BLOCK_BYTES = 8;

export const AES_KEY_BYTES = 32;
export const AES_KEY_LENGTH_BITS = AES_KEY_BYTES * BITS_PER_BYTE;
export const AES_GCM_IV_BYTES = 12;
export const AES_GCM_AUTH_TAG_BYTES = 16;
export const AES_GCM_AUTH_TAG_BITS = AES_GCM_AUTH_TAG_BYTES * BITS_PER_BYTE;
export const AES_KW_WRAPPED_KEY_BYTES = AES_KEY_BYTES + AES_KW_INTEGRITY_BLOCK_BYTES;
